### ISSUE TITLE
Build Error：An error occurred during the fetch of repository 'breakpad' when “bazel build pkg”

### ISSUE THREAD

**Issue by Luftschloss** [google/agi#1009]
Environment information:
 - AGI version:2.1.0
 - Host OS:Windows 10
 - Bazel version:4.0.0

Description:
fetch repository error when build, full log is below:
```
INFO: Repository breakpad instantiated at:
  D:/workspace/agi-2.1.0/WORKSPACE:22:19: in <toplevel>
  C:/users/vip/_bazel_vip/j7xxzcsd/external/gapid/tools/build/workspace.bzl:122:21: in gapid_dependencies
  C:/users/vip/_bazel_vip/j7xxzcsd/external/gapid/tools/build/rules/repository.bzl:49:18: in maybe_repository
Repository rule breakpad defined at:
  C:/users/vip/_bazel_vip/j7xxzcsd/external/gapid/tools/build/third_party/breakpad.bzl:37:27: in <toplevel>
WARNING: Download from https://chromium.googlesource.com/breakpad/breakpad/+archive/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz failed: class java.net.ConnectException Connection refused: connect
ERROR: An error occurred during the fetch of repository 'breakpad':
   Traceback (most recent call last):
        File "C:/users/vip/_bazel_vip/j7xxzcsd/external/gapid/tools/build/third_party/breakpad.bzl", line 20, column 40, in _breakpad_impl
                repository_ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://chromium.googlesource.com/breakpad/breakpad/+archive/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz] to C:/users/vip/_bazel_vip/j7xxzcsd/external/breakpad/temp2337545407938820909/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz: Connection refused: connect
ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/vip/_bazel_vip/j7xxzcsd/external/gapid/tools/build/third_party/breakpad.bzl", line 20, column 40, in _breakpad_impl
                repository_ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://chromium.googlesource.com/breakpad/breakpad/+archive/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz] to C:/users/vip/_bazel_vip/j7xxzcsd/external/breakpad/temp2337545407938820909/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz: Connection refused: connect
ERROR: D:/workspace/agi-2.1.0/core/cc/BUILD.bazel:18:11: //core/cc:cc depends on @breakpad//:breakpad in repository @breakpad which failed to fetch. no such package '@breakpad//': java.io.IOException: Error downloading [https://chromium.googlesource.com/breakpad/breakpad/+archive/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz] to C:/users/vip/_bazel_vip/j7xxzcsd/external/breakpad/temp2337545407938820909/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz: Connection refused: connect
ERROR: Analysis of target '//:pkg' failed; build aborted: Analysis failed
INFO: Elapsed time: 29.122s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (340 packages loaded, 24031 targets configured)
    Fetching @perfetto; Cloning d1a7b031bbded67e0d67957974e85a83e0b815c0 of https://android.googlesource.com/platform/external/perfetto 28s
    Fetching @org_golang_x_mod; fetching 27s
    Fetching @org_golang_google_grpc; fetching 27s
    Fetching @org_golang_x_crypto; fetching 27s
    Fetching @org_golang_x_net; fetching 27s
```

Additional information:
I could download "breakpad" by the url(https://chromium.googlesource.com/breakpad/breakpad/+archive/a61afe7a3e865f1da7ff7185184fe23977c2adca.tar.gz) from broswer, but bazel download faild, is there any way to config local_repository avoid this?

**Comment by pmuetschard** [comment]
Are you behind proxies? This may be transient, is it still an issue for you?

**Comment by Luftschloss** [comment]
> 
no proxies，can't fetch repository by bazel

**Comment by pmuetschard** [comment]
If this is still happening, it must be due to some firewall between you and `chromium.googlesource.com` or your DNS is giving you the wrong IP. The URL it prints is correct and works/has been working. try `telnet chromium.googlesource.com 443` from your terminal and see if you get the connection refused error there as well.

There's nothing we can do from our side, here.
