### ISSUE TITLE
java.lang.NullPointerException at com.google.gapid.views.PipelineView.lambda$createPipelineTabs$4(PipelineView.java:272)

### ISSUE THREAD

**Issue by liushaofang** [google/agi#1074]
**Environment information:**
 - AGI version: agi-3.0.0
 - Host OS: macos catalina 10.15.5 (19F101)
 If tracing on Android:
 - Device model: Google Pixel 4 XL
 - Android Version: Android 12

**Bug description**
Report "The application encountered an error:Unhandled exception in the UI thread." Error on Performance pane 

**Reproduction steps**
1. Capture trace
2. Configure Device and Type  and select Frame Profile - OpenGL on ANGLE
3. Choose the opengl demo app
4. Select Manual under Start and Duration section
5. Configure Ouput as needed
6. Click ok  - start -stop to get profile
7. Select Performance pane and click command below RenderPass
8. Error dialog with stack trace shows

**Stacktrace**
The application encountered an error: Unhandled exception in the UI thread.
java.lang.NullPointerException
	at com.google.gapid.views.PipelineView.lambda$createPipelineTabs$4(PipelineView.java:272)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1270)
	at org.eclipse.swt.widgets.Button.drawWidget(Button.java:547)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:776)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6124)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5398)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5802)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:92)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3877)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:67)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:59)
	at com.google.gapid.Main$UI.lambda$registerWindowExceptionHandler$0(Main.java:133)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:140)
	at com.google.gapid.Main.main(Main.java:80)
**Screenshots**
![AndroidGpuInspectorError](https://user-images.githubusercontent.com/4708262/162136186-3d8a35df-f7aa-46c0-9980-ad63b4ecc6ef.png)
**Additional debugging information**
code snippet from PipelineView.java
`
stageButton.addListener(SWT.Paint, e -> {
    Rectangle areaSize = stageButton.getBounds();
    e.gc.setLineWidth((int)(areaSize.height * 0.1));
    if (hoveredButton == stageButton || stageMap.get(selectedStage).stageButton == stageButton) {
        e.gc.setForeground(getDisplay().getSystemColor(SWT.COLOR_BLUE));
    } else {
        e.gc.setBackground(getDisplay().getSystemColor(SWT.COLOR_LIST_FOREGROUND));
    }
    e.gc.drawPolygon(new int[] {0, 0, areaSize.width - 1, 0, areaSize.width - 1, areaSize.height - 1, 0, areaSize.height - 1});
});
`
gfxtrace file with error reported above.
[error_angle_20220406_2140.gfxtrace.zip](https://github.com/google/agi/files/8440299/error_angle_20220406_2140.gfxtrace.zip)

**Comment by tjudemon** [comment]
The same problem troubled me.

**Comment by ttanatb** [comment]
Hi all, thanks for reporting this issue! We're looking into the issue and trying to include a fix by next release.

In the meantime, the workaround is:
- When viewing a trace file, on the top-left corner click on 'View' > 'Tabs' > 'Pipeline' to hide the 'Pipeline' tab.
![Screenshot from 2022-04-07 16-00-18](https://user-images.githubusercontent.com/14023901/162229846-53bf2400-4c4b-4e25-9336-80ef680edac1.png)

This will prevent the error from showing up when you expand the draw call in the command tree.
