### ISSUE TITLE
gpu inspector ui error

### ISSUE THREAD

**Issue by ajaning** [google/agi#1080]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model:
 - Android Version:

**Bug description**

**Reproduction steps**

**Stacktrace**
Please paste a stacktrace here if it's available.

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by ajaning** [comment]
java.lang.NullPointerException
	at com.google.gapid.views.CommandTree.getValue(CommandTree.java:1017)
	at com.google.gapid.views.CommandTree.updateHover(CommandTree.java:1151)
	at com.google.gapid.views.CommandTree.lambda$new$10(CommandTree.java:251)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:140)
	at com.google.gapid.Main.main(Main.java:80)

**Comment by ttanatb** [comment]
Hi, thanks for reporting this! If you could provide more context (e.g. screenshots/logs), that would be greatly appreciated -- thanks!

**Comment by ttanatb** [comment]
The particular stack trace you attached looks similar to a bug we fixed a while back. So I'll close out this issue for now. Feel free to re-open if you're still running into this crash with the new release.
