### ISSUE TITLE
Support for VK_KHR_timeline_semaphore

### ISSUE THREAD

**Issue by AlexanderVeselov-arm** [google/agi#1112]
Hi, AGI team! We trying to use AGI for internal content, yet unfortunately we unable to use frame profiler due to lack of [VK_KHR_timeline_semaphore](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_timeline_semaphore.html) support. Please consider to add this one in future releases, thanks!

**Environment information:**
 - AGI version: 3.0.1
 - Host OS: Windows-10
 - Device model: Galaxy S21 5G
 - Android Version: 11

**Bug description**
Once trace capturing is done, error pop-up:
```
Failed to profile the replay
  Cause: Replay returned error
  Cause: Missing switch case handler for value vulkan.VkStructureType VkStructureType(1000207003)
```

Note: `1000207003` is value of `VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO`

**Stacktrace**
```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.reflect.UndeclaredThrowableException)
	at org.eclipse.swt.SWT.error(SWT.java:4893)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:140)
	at com.google.gapid.Main.main(Main.java:80)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy9.onCommandsLoaded(Unknown Source)
	at com.google.gapid.models.CommandStream.fireLoadedEvent(CommandStream.java:181)
	at com.google.gapid.models.ModelBase.updateError(ModelBase.java:120)
	at com.google.gapid.models.ModelBase$1.onUiThreadError(ModelBase.java:85)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:36)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:25)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:141)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:169)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:161)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.gapid.util.Events$ListenerCollectionImpl.invoke(Events.java:167)
	... 18 more
Caused by: java.lang.NullPointerException
	at com.google.gapid.views.CommandTree$TreeState.expandChildren(CommandTree.java:1362)
	at com.google.gapid.views.CommandTree$TreeState.reset(CommandTree.java:1294)
	at com.google.gapid.views.CommandTree.onCommandsLoaded(CommandTree.java:542)
	... 23 more
```

**Comment by ttanatb** [comment]
Hi, thanks for reporting this issue.

We haven't quite got around to adding support for [VK_KHR_timeline_semaphore](https://developer.android.com/agi/vulkan-extensions#:~:text=VK_KHR_timeline_semaphore,No) yet but this can help us increase the priority on supporting this extension.
