### ISSUE TITLE
The application encountered an error: Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by linxs0211** [google/agi#1123]
**Environment information:**
 - AGI version:
 - Host OS: [e.g. Linux]
 If tracing on Android:
 - Device model: pixel4
 - Android Version: Android12

**Bug description**
Crash happened when Click the RenderPass Item in Performance Tab
![image](https://user-images.githubusercontent.com/55836257/172434509-0738d5eb-896b-44b6-99ec-295b7cad2b32.png)

**Reproduction steps**

**Stacktrace**
java.lang.NullPointerException
	at com.google.gapid.views.PipelineView.lambda$createPipelineTabs$4(PipelineView.java:272)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1270)
	at org.eclipse.swt.widgets.Button.drawWidget(Button.java:547)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:776)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6124)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5398)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5802)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:92)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3877)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:67)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:59)
	at com.google.gapid.Main$UI.lambda$registerWindowExceptionHandler$0(Main.java:133)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:140)
	at com.google.gapid.Main.main(Main.java:80)

**Screenshots**

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by ttanatb** [comment]
Thanks for reporting this, could you provide more info to this issue?

Specifically, if you could provide the following, it'll really help with triaging this issue:
- **Version** -- this is found in `Help > About` from the top menu 
- gapis.log & gapic.log -- this is found in `Help > Open Log Directory`

**Comment by pmuetschard** [comment]
I think this has been fixed in 3.0.1 release. Can you please confirm the version of AGI you are using and try 3.0.1?

**Comment by ttanatb** [comment]
Closing this issue due to staleness, please let us know if you still run into this problem in the latest release
