### ISSUE TITLE
Unhandled exception in the UI thread

### ISSUE THREAD

**Issue by GainLee** [google/agi#1155]
**Environment information:**
 - AGI version:2022-3.0.1
 - Host OS: [e.g. Linux] MacOS 11.6.6 
 If tracing on Android:
 - Device model: Pixel 4 
 - Android Version: Android 12

**Bug description**
The application encountered an error when opening a frame trace

**Reproduction steps**
Capture frame trace with "start at beginning" and open it

**Stacktrace**
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.reflect.UndeclaredThrowableException)
	at org.eclipse.swt.SWT.error(SWT.java:4893)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4262)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3885)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:140)
	at com.google.gapid.Main.main(Main.java:80)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy9.onCommandsLoaded(Unknown Source)
	at com.google.gapid.models.CommandStream.fireLoadedEvent(CommandStream.java:181)
	at com.google.gapid.models.ModelBase.updateError(ModelBase.java:120)
	at com.google.gapid.models.ModelBase$1.onUiThreadError(ModelBase.java:85)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:36)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:25)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:141)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:169)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:161)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.gapid.util.Events$ListenerCollectionImpl.invoke(Events.java:167)
	... 18 more
Caused by: java.lang.NullPointerException
	at com.google.gapid.views.CommandTree$TreeState.expandChildren(CommandTree.java:1362)
	at com.google.gapid.views.CommandTree$TreeState.reset(CommandTree.java:1294)
	at com.google.gapid.views.CommandTree.onCommandsLoaded(CommandTree.java:542)
	... 23 more

**Screenshots**
<img width="713" alt="image" src="https://user-images.githubusercontent.com/2909095/179915390-dc2a1a4a-f878-4f69-b4de-a76e84dc85ef.png">

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
[gapis.log](https://github.com/google/agi/files/9147193/gapis.log)
[gapic.log](https://github.com/google/agi/files/9147196/gapic.log)

- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.
[logcat-full.txt](https://github.com/google/agi/files/9147212/logcat-full.txt)

**Comment by ttanatb** [comment]
Thanks for reporting this -- quick questions:
- Does this only occur when capturing with "start at beginning" or does it also happen when capturing from the middle of the game?
- Does your game use the `VkDebugUtilsMessengerCreateInfoEXT` struct?

It looks like we're missing the definition for `VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT` and `VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT` in the [enums.api file](https://github.com/google/agi/blob/master/gapis/api/vulkan/api/enums.api#L189)

**Comment by GainLee** [comment]
> * VkDebugUtilsMessengerCreateInfoEXT

Yeah, I used VkDebugUtilsMessengerCreateInfoEXT.

I think this occurs not only when capturing with "start at beginning", but I'll also confirm that later.

**Comment by GainLee** [comment]
> Thanks for reporting this -- quick questions:
> 
> * Does this only occur when capturing with "start at beginning" or does it also happen when capturing from the middle of the game?
> * Does your game use the `VkDebugUtilsMessengerCreateInfoEXT` struct?
> 
> It looks like we're missing the definition for `VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT` and `VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT` in the [enums.api file](https://github.com/google/agi/blob/master/gapis/api/vulkan/api/enums.api#L189)

I have confirmed that it occurs only when capturing with "start at beginning" and I used VkDebugUtilsMessengerCreateInfoEXT.
