### ISSUE TITLE
Support and ship Macos ARM builds?

### ISSUE THREAD

**Issue by oscarbg** [google/agi#1390]
Hi,
testing 3.3.2 latest release (https://github.com/google/agi/releases/tag/v3.3.2) on a Mac ARM but 
agi-3.3.2-macos.dmg  seems is amd64 only..
thought it will work via rosetta but fails due to swt:

>Could not load SWT library

any easy fix?
full log:
```
/Applications/AGI.app/Contents/MacOS/agi         
Starting /usr/bin/java /Applications/AGI.app/Contents/MacOS/lib/gapic.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4952r11 in java.library.path: /Users/obg/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt-cocoa in java.library.path: /Users/obg/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt in java.library.path: /Users/obg/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib: dlopen(/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib, 0x0001): tried: '/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib' (no such file), '/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
	Can't load library: /Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	Can't load library: /Users/obg/.swt/lib/macosx/aarch64/libswt.jnilib
	/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib: dlopen(/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib, 0x0001): tried: '/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib' (no such file), '/Users/obg/.swt/lib/macosx/aarch64/libswt-cocoa-4952r11.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.internal.cocoa.NSMutableArray.arrayWithCapacity(NSMutableArray.java:39)
	at org.eclipse.swt.widgets.Canvas.<clinit>(Canvas.java:55)
	at com.google.gapid.Main.<clinit>(Main.java:249) 
```

any

**Comment by olehkuznetsov** [comment]
Should be fixed in this one: [v3.3.3 dev](https://github.com/google/agi-dev-releases/releases/tag/v3.3.3-dev-20241220)

**Comment by rafrafek** [comment]
Any update on this? I tried `agi-2025-3.3.3-macos.dmg` today and it still prompts for Rosetta.

Apple plans to remove most general-purpose Rosetta 2 functionality starting with macOS 28 (2027), so there's still some time, but avoiding a Rosetta dependency already would be great.
