### ISSUE TITLE
Failed to take trace upon manual start

### ISSUE THREAD

**Issue by zhangyiwei** [google/agi#393]
**Environment information:**
 - AGI version: ToT
 - Host OS: [e.g. Linux] macOS Catalina
 If tracing on Android:
 - Device model: Pixel 4 XL
 - Android Version: ToT

**Bug description**
I chose manual start. Then upon the scene I was interested, I clicked start.

**Reproduction steps**
Steps to reproduce the behavior: Seen a couple time. Not sure about repro steps

**Stacktrace**
The application encountered an error:
Tracing Failed
   Cause: Failed during tracing session
   Cause: EOF

Please check the logs for details.
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Failed during tracing session
   Cause: EOF
	at com.google.gapid.server.Client.throwIfError(Client.java:310)
	at com.google.gapid.server.Client.lambda$streamTrace$55(Client.java:284)
	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:225)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:436)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:658)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:643)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()
	at com.google.gapid.server.Client.streamTrace(Client.java:281)
	at com.google.gapid.server.Tracer.trace(Tracer.java:41)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:176)
	at com.google.gapid.MainWindow.lambda$updateFileMenu$11(MainWindow.java:307)
	at com.google.gapid.MainWindow$MenuItems$1.run(MainWindow.java:517)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4387)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4174)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3791)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:128)
	at com.google.gapid.Main.main(Main.java:77)

**Screenshots**

**Additional debugging information**
[logcat-full.txt](https://github.com/google/agi/files/4941178/logcat-full.txt)
[gapic.log](https://github.com/google/agi/files/4941175/gapic.log)
[gapis.log](https://github.com/google/agi/files/4941176/gapis.log)

**Comment by lpy** [comment]
Looks like a dup to b/161645305

**Comment by lpy** [comment]
Speculatively fixed by https://github.com/google/agi/pull/407
