### ISSUE TITLE
Does not work with targetSdkVersion 30

### ISSUE THREAD

**Issue by yjh0502** [google/agi#620]
**Environment information:**
 - AGI version:1.0
 - Host OS: Windows 10
 If tracing on Android:
 - Device model: Google Pixel 4 XL
 - Android Version: 11

**Bug description**
AGI does not work when a target app is build with targetSdkVersion 30.

**Reproduction steps**
Build an app with targetSdkVersion 30.
Trying to capture a trace with AGI

**Stacktrace**
```
01-07 01:09:32.666   613   613 E SELinux : avc:  denied  { find } for pid=2859 uid=10224 name=tethering scontext=u:r:permissioncontroller_app:s0:c224,c256,c512,c768 tcontext=u:object_r:tethering_service:s0 tclass=service_manager permissive=0
01-07 01:09:32.677  5438  5438 I GraphicsEnvironment: GPU debug layers enabled for com.foo.sl
01-07 01:09:32.677  5438  5438 I GraphicsEnvironment: GPU debug layer apps: com.google.android.gapid.arm64v8a:com.google.pixel.coral.gpuprofiling.vulkanlayer
01-07 01:09:32.678  1508  7824 I AppsFilter: interaction: PackageSetting{62f85b8 com.foo.sl/10242} -> PackageSetting{c60877a com.google.android.gapid.arm64v8a/10233} BLOCKED
01-07 01:09:32.678  5438  5438 W GraphicsEnvironment: Debug layer app 'com.google.android.gapid.arm64v8a' not installed
01-07 01:09:32.678  5438  5438 D AndroidRuntime: Shutting down VM
01-07 01:09:32.679  5438  5438 E AndroidRuntime: FATAL EXCEPTION: main
01-07 01:09:32.679  5438  5438 E AndroidRuntime: Process: com.foo.sl, PID: 5438
01-07 01:09:32.679  5438  5438 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.ApplicationInfo.primaryCpuAbi' on a null object reference
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.os.GraphicsEnvironment.chooseAbi(GraphicsEnvironment.java:888)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.os.GraphicsEnvironment.getDebugLayerAppPaths(GraphicsEnvironment.java:253)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.os.GraphicsEnvironment.getDebugLayerPathsFromSettings(GraphicsEnvironment.java:227)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:841)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.LoadedApk.getClassLoader(LoadedApk.java:958)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.LoadedApk.getResources(LoadedApk.java:1190)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.ContextImpl.createAppContext(ContextImpl.java:2659)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.ContextImpl.createAppContext(ContextImpl.java:2651)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-07 01:09:32.679  5438  5438 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-07 01:09:32.681  1508  6586 W ActivityTaskManager:   Force finishing activity com.foo.sl/com.unity3d.player.UnityPlayerActivity
```

Here's a problematic part
```
AppsFilter: interaction: PackageSetting{62f85b8 com.foo.sl/10242} -> PackageSetting{c60877a com.google.android.gapid.arm64v8a/10233} BLOCKED
```
Related: https://developer.android.com/about/versions/11/privacy/package-visibility
The same app works as expected when built with targetSdkVersion 29.

**Screenshots**
N/A

**Additional debugging information**
- Please attach the generated _gapis.log_ and _gapic.log_ files you will find in the temp folder (e.g. /tmp/ on linux).
- If using Android: Please attach a full logcat dump (```adb logcat -d > logcat-full.txt```) that contains logs since AGI was started.

**Comment by hevrard** [comment]
Thanks for reporting!

I think https://github.com/google/agi/pull/601 fixes this. The next AGI dev-release (https://github.com/google/agi-dev-releases) will contain this fix, but as of today the latest dev-release does not contain it. There should be a new dev-release by the end of the week, if you're in a hurry to get the fix in the meantime you'll need to compile AGI top-of-tree.

**Comment by hevrard** [comment]
@yjh0502 please try the latest dev-release that contains the fix:
https://github.com/google/agi-dev-releases/releases/latest

If this doesn't fix your issue, please let us know here by re-opening this github issue.
Thanks!
