### ISSUE TITLE
The application encountered an error:

### ISSUE THREAD

**Issue by heshiqi** [google/agi#640]
**Environment information:**
 - AGI version:1.0.0:4ddd08c5546200a14141b75639a4b758fb2fadd2
 - Host OS:  mac
 If tracing on Android:
 - Device :pixel4 
 - Android Version:11 api 30

**Bug description**
The application encountered an error:

The server has exited with an error code of: 2 
Most functions in AGI are unavailable without a server. 
You can restart the server, exit AGI, or close the dialog to continue without a server.

Please check the logs for details.

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3793)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.views.TracerDialog.loadDevicesAndShowDialog(TracerDialog.java:194)
	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:173)
	at com.google.gapid.LoadingScreen.lambda$createOptions$0(LoadingScreen.java:119)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4387)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4174)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3791)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:134)
	at com.google.gapid.Main.main(Main.java:80)
Caused by: java.lang.NullPointerException
	at com.google.gapid.views.TracerDialog$TraceInputDialog$TraceInput.setValidationStatus(TracerDialog.java:648)
	at com.google.gapid.views.TracerDialog$TraceInputDialog$TraceInput$5.onUiThreadError(TracerDialog.java:641)
	at com.google.gapid.views.TracerDialog$TraceInputDialog$TraceInput$5.onUiThreadError(TracerDialog.java:621)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:36)
	at com.google.gapid.rpc.UiErrorCallback.onUiThread(UiErrorCallback.java:25)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:135)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:163)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:155)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 19 more

**Comment by hevrard** [comment]
Thanks for reporting! It looks like you're using the stable build release that dates back from September. Can you try to use the latest dev-release, that you can grab from: https://github.com/google/agi-dev-releases/releases/latest ?

Please re-open if you can reproduce with the latest dev-release. Thanks!

**Comment by heshiqi** [comment]
> Thanks for reporting! It looks like you're using the stable build release that dates back from September. Can you try to use the latest dev-release, that you can grab from: https://github.com/google/agi-dev-releases/releases/latest ?
> 
> Please re-open if you can reproduce with the latest dev-release. Thanks!

It's still not solved

**Comment by hevrard** [comment]
I see you're on Mac, this recent PR https://github.com/google/agi/pull/650 updates some UI libraries and might fix your issue. The next dev-release should contain this change.

@stellama0208 what do you think?

**Comment by hevrard** [comment]
@heshiqi the latest dev-release version (released a few minutes ago) has the UI library updates change in it, can you give it a try and tell us if your issue is still there?

https://github.com/google/agi-dev-releases/releases/latest

**Comment by stellama0208** [comment]
Hi @heshiqi, would you mind check and let us know your current macOS version, which could be found by clicking the top-left apple icon -> select "About this mac"? 
And if you still meet the same problem after you try the newest build above mentioned by Hugues, would you mind paste the new error stack trace again? In this way we can align the error's line number with our current codebase, and help solve the problem, thanks for your testing!

**Comment by pau-baiget** [comment]
@heshiqi , we haven't heard from you for more than 30 days so we'll proceed to close this as resolved. Please re-open if you can provide answers to the latest questions from my fellow colleagues. Thank you!!
