### ISSUE TITLE
Device support validation fails for Samsung Galaxy S10 (SM-G973F)

### ISSUE THREAD

**Issue by rafaelvcaetano** [google/agi#652]
**Environment information:**
 - AGI version: AGI 1.0.0
 - Host OS: Windows 10
 - Device model: Samsung Galaxy S10 (SM-G973F)
 - Android Version: 11

**Bug description**
AGI reports "Device support validation failed" for Samsung Galaxy S10 (SM-G973F) running Android 11.

**Reproduction steps**
1. Connect device to PC
2. Open AGI
3. Select "Capture a new trace"
4. Wait for device list to load
5. Select Samsung Galaxy S10 entry
6. Observe

**Screenshots**
![image](https://user-images.githubusercontent.com/9086379/105753101-15031000-5f40-11eb-8e2a-75b86b9a16de.png)

**Additional debugging information**
[gapis.log](https://github.com/google/agi/files/5869042/gapis.log)
[gapic.log](https://github.com/google/agi/files/5869044/gapic.log)

Logcat (filtered by "gapid"):
[logcat.txt](https://github.com/google/agi/files/5869064/logcat.txt)

**Comment by jakon2048** [comment]
Hi, I followed up with Samsung about this and it seems like AGI support for the Mali versions of Note 10 and S10 are not out yet. I will update the device validation page with the latest information and will update this once we receive word on when it will be out.

**Comment by rafaelvcaetano** [comment]
Just an update, after several OS updates, I decided to try again using the same AGI version and the "Device support validation passed." message is shown. After starting the capture, the app is launched but it crashes immediately. The following stack trace can be found in the logs:

```
2021-04-22 18:29:12.216 16528-16528/<package_name> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <package_name>, PID: 16528
    java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.ApplicationInfo.primaryCpuAbi' on a null object reference
        at android.os.GraphicsEnvironment.chooseAbi(GraphicsEnvironment.java:1088)
        at android.os.GraphicsEnvironment.getDebugLayerAppPaths(GraphicsEnvironment.java:304)
        at android.os.GraphicsEnvironment.getDebugLayerPathsFromSettings(GraphicsEnvironment.java:278)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:872)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:1016)
        at android.app.LoadedApk.getResources(LoadedApk.java:1260)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2788)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7329)
        at android.app.ActivityThread.access$1500(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

![image](https://user-images.githubusercontent.com/9086379/115780858-90465780-a3b1-11eb-8466-24f3733fabf0.png)

Attempting to launch the app again manually also generates the same error and it will only open if I manually uninstall the GAPID app.

**Comment by jakon2048** [comment]
Thanks. Let me forward this to our engineers.

**Comment by hevrard** [comment]
@lpy this looks like a bug in GraphicsEnvironment that you fixed with https://cs.android.com/android/_/android/platform/frameworks/base/+/eb1c5a4c28ec7cd2577e7182ed249a8ec4cc4c0b, could it be that Samsung didn't picked it up yet?

**Comment by lpy** [comment]
We have fixed this bug on the platform side and it was rolled out through quarterly platform release. It looks like the build on this Samsung phone doesn't have the fix

**Comment by hevrard** [comment]
@rafaelvcaetano in the long term, a future system update from Samsung should bring the Android fix this gets rid of this issue.

In the meantime, you might be able to work around this issue by uninstalling AGI APKs manually:

```
adb shell uninstall com.google.android.gapid.armeabiv7a
adb shell uninstall com.google.android.gapid.arm64v8a
```

And then restarting AGI. Could you please try this (and re-try a few times if it still fails), and let us know if that unblocks you?

**Comment by rafaelvcaetano** [comment]
I tried the workaround a few times but the problem still persists.

I will wait for the next updates and I will let you know if the problem is fixed or a different outcome is produced.

**Comment by hevrard** [comment]
@rafaelvcaetano sorry to hear that. As a last resort you can maybe try our unstable but more recent AGI dev-release, to see if that makes any difference:
https://github.com/google/agi-dev-releases/releases/latest

**Comment by rafaelvcaetano** [comment]
Thanks for the suggestion! So, I tried the latest dev release and that actually seemed to fix the problem. The app is now launched automatically without crashing and I can perform captures without issues!
