### ISSUE TITLE
Compile error for v2.1.0

### ISSUE THREAD

**Issue by zhangfuwen** [google/agi#985]
by the way, do we have a standard docker image for building this project? 

**Environment information:**
 - AGI version: v2.1.0
 - Host OS: Ubuntu 21.10
 If tracing on Android:
 - Device model: NA
 - Android Version: NA

**Bug description**
trying to compile from source code, and error occurred on both master and v2.1.0.

**Reproduction steps**

run `bazel build pkg`

**Stacktrace**
ERROR: /data1/XR/agi/gapii/cc/BUILD.bazel:32:13: apic compiling apis for k8 failed: (Exit 2): apic failed: error executing command 
  (cd /home/zhangfuwen/.cache/bazel/_bazel_zhangfuwen/c95f9544164f9bf1de98e4d4765ddedb/sandbox/linux-sandbox/4007/execroot/gapid && \
  exec env - \
    PATH=/home/zhangfuwen/bin/node-v14.17.1-linux-x64/bin:/home/zhangfuwen/perl5/bin:/home/zhangfuwen/bin/node-v14.17.1-linux-x64/bin:/home/zhangfuwen/perl5/bin:/home/zhangfuwen/.cargo/bin:/home/zhangfuwen/.local/bin:/home/zhangfuwen/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/zhangfuwen/bin/dywt/ef/bin:/home/zhangfuwen/bin/platform-tools_r30.0.4-linux/platform-tools/:/usr/local/lib/node_modules/yarn/bin:/home/zhangfuwen/bin/blender-2.93.1-linux-x64:/home/zhangfuwen/.local/share/gem/ruby/2.7.0/bin:/home/zhangfuwen/bin/platform-tools_r30.0.4-linux/platform-tools/:/usr/local/lib/node_modules/yarn/bin:/home/zhangfuwen/bin/blender-2.93.1-linux-x64:/home/zhangfuwen/.local/share/gem/ruby/2.7.0/bin \
  bazel-out/host/bin/cmd/apic/apic_/apic compile --search .,bazel-out/k8-fastbuild/bin --target k8 --capture '' --module '' --output bazel-out/k8-fastbuild/bin/gapii/cc/apis_compiled.o '--optimize=True' '--dump=False' --namespace gapii --symbols c++ --emit-encode gapis/api/vulkan/vulkan.api)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc095d16c pc=0x7ff9bb1ff035]

runtime stack:
runtime.throw({0x277a175, 0x0})
	GOROOT/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	GOROOT/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
runtime.cgocall(0xf47cf0, 0xc0043e9790)
	GOROOT/src/runtime/cgocall.go:156 +0x5c fp=0xc0043e9768 sp=0xc0043e9730 pc=0x8ba7bc
github.com/google/gapid/core/os/device/host._Cfunc_get_device_instance()
	_cgo_gotypes.go:116 +0x4a fp=0xc0043e9790 sp=0xc0043e9768 pc=0xca4cca
github.com/google/gapid/core/os/device/host.getHostDevice()
	/home/zhangfuwen/.cache/bazel/_bazel_zhangfuwen/c95f9544164f9bf1de98e4d4765ddedb/sandbox/linux-sandbox/2983/execroot/gapid/core/os/device/host/host_c.go:29 +0x78 fp=0xc0043e9848 sp=0xc0043e9790 pc=0xca4db8
github.com/google/gapid/core/os/device/host.Instance.func1()
	host.go:32 +0x2b fp=0xc0043e9908 sp=0xc0043e9848 pc=0xca50cb
sync.(*Once).doSlow(0x100000000000012, 0x7ff9e86e5628)
	GOROOT/src/sync/once.go:68 +0xd2 fp=0xc0043e9970 sp=0xc0043e9908 pc=0x929e32
sync.(*Once).Do(...)
	GOROOT/src/sync/once.go:59
github.com/google/gapid/core/os/device/host.Instance({0x10000f9f00e6f70, 0x7ff9e86e5628})
	host.go:32 +0x31 fp=0xc0043e9990 sp=0xc0043e9970 pc=0xca4b91
github.com/google/gapid/gapil/compiler.Compile({0xc000140088, 0x1, 0x1}, 0xc0001308a0, {{0x7ffc18353c26, 0x0}, 0xc000180b90, 0xc000180b90, 0x278cc18, {0xc003955a00, ...}, ...})
	/home/zhangfuwen/.cache/bazel/_bazel_zhangfuwen/c95f9544164f9bf1de98e4d4765ddedb/sandbox/linux-sandbox/2753/execroot/gapid/gapil/compiler/compiler.go:115 +0x5c fp=0xc0043e9a58 sp=0xc0043e9990 pc=0xde05dc
main.(*compileVerb).Run(0xc00012a800, {0x2855200, 0xc00012d170}, {0xc00013e1b0, {0x0, 0x0}, 0x1, 0xc00012d1d0, 0xc00012ccf0, {0xc000136720, ...}, ...})
	cmd/apic/compile.go:157 +0x31a fp=0xc0043e9b98 sp=0xc0043e9a58 pc=0xf457fa
github.com/google/gapid/core/app.(*Verb).Invoke(0x3787bc0, {0x2855200, 0xc00012d170}, {0xc000136600, 0x13, 0x20})
	core/app/verbs.go:92 +0x265 fp=0xc0043e9ce0 sp=0xc0043e9b98 pc=0xcadea5
github.com/google/gapid/core/app.VerbMain({0x2855200, 0xc00012d170})
	core/app/verbs.go:123 +0x46 fp=0xc0043e9d20 sp=0xc0043e9ce0 pc=0xcae186
github.com/google/gapid/core/app.doRun(0x278ca50)
	core/app/run.go:307 +0x7a2 fp=0xc0043e9f50 sp=0xc0043e9d20 pc=0xcacee2
github.com/google/gapid/core/app.Run(0xc0000001a0)
	core/app/run.go:200 +0x19 fp=0xc0043e9f68 sp=0xc0043e9f50 pc=0xcac719
main.main()
	cmd/apic/main.go:23 +0x57 fp=0xc0043e9f80 sp=0xc0043e9f68 pc=0xf461d7
runtime.main()
	GOROOT/src/runtime/proc.go:255 +0x227 fp=0xc0043e9fe0 sp=0xc0043e9f80 pc=0x8eed27
runtime.goexit()
	GOROOT/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0043e9fe8 sp=0xc0043e9fe0 pc=0x91fa41

goroutine 34 [syscall]:
os/signal.signal_recv()
	GOROOT/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	GOROOT/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	GOROOT/src/os/signal/signal.go:151 +0x2c

**Screenshots**
NA

**Additional debugging information**
NA

**Comment by pmuetschard** [comment]
It's crashing when trying to determine the host's device info. Can you try `bazel -c dbg run //cmd/device-info` and paste the output here? If it crashes, could you try running the binary (`./bazel-bin/cmd/device-info/device-info`) with gdb and post the stack trace of the crash, please?
